services:
  fakeponse:
    image: fakeponse:latest
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
    volumes:
      - ./:/var/www/html
    networks:
      - fakeponse
  postgresql:
    image: dhi.io/postgres:18-alpine3.22
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: fakeponse
    volumes:
      - fakeponse-postgresql-data:/var/lib/postgresql
    networks:
      - fakeponse
  auth-microservice:
    image: tomi0/auth-microservice:latest
    container_name: auth-microservice
    ports:
      - "8001:80"
    environment:
      APP_ENV: "production"
      DB_HOST: "auth-microservice_db"
      DB_PORT: "3306"
      DB_DATABASE: "auth"
      DB_USERNAME: "user"
      DB_PASSWORD: "secret"
    networks:
      - fakeponse
  auth-microservice_db:
    image: mysql:8.4.6
    container_name: auth-microservice_db
    volumes:
      - auth_db_volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - fakeponse
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'

networks:
  fakeponse:
    driver: bridge

volumes:
  fakeponse-postgresql-data:
    driver: local
  auth_db_volume:
    driver: local
