services:
  fakeponse:
    image: fakeponse:latest
    ports:
      - "8000:80"
    environment:
      APP_ENV: production
      APP_KEY: base64:MAkdKa7dEJ2tpMIgKiHOyEAOGW/X0FvJFzFdyIpaQ8M=
#    volumes:
#      - ./:/var/www/html
